### ISSUE TITLE
Add error page

### ISSUE THREAD

**Issue by Katin0104** [Katin0104/BeanThereDoneThat#3]
### Add Error Page

**Description:**
We need to create a custom error page for our SvelteKit application that uses TypeScript and DaisyUI. This page will handle various HTTP errors and provide a user-friendly message to the users.

**Tasks:**

- [ ] **Create Error Page Component:**
  - Create a new file `+error.svelte` in the appropriate route folder.
  - Use DaisyUI components to style the error page.

- [ ] **Implement Error Handling in Load Function:**
  - Modify existing `load` functions to throw appropriate errors using SvelteKit's `error` function.
  - Ensure that the errors include relevant HTTP status codes and messages.

- [ ] **Style the Error Page:**
  - Use DaisyUI to make the error page visually appealing.
  - Include a message that indicates the type of error and any relevant information.

- [ ] **Test Error Page:**
  - Trigger various errors (e.g., 404 Not Found, 500 Internal Server Error) and ensure the custom error page is displayed correctly.
  - Verify that the error page displays the correct status code and message.

**Additional Notes:**
- Ensure the error page is responsive and works well on different devices.
- Consider adding a link or button to navigate back to the homepage or previous page.

**Example Code:**

1. **Create the Error Page Component:**

   ```svelte
   <!-- src/routes/+error.svelte -->
   <script context="module" lang="ts">
     export function load({ error, status }) {
       return {
         props: {
           error,
           status
         }
       };
     }
   </script>

   <script lang="ts">
     export let error: { message: string };
     export let status: number;
   </script>

   <div class="flex flex-col items-center justify-center min-h-screen bg-gray-100 text-center">
     <h1 class="text-6xl font-bold text-red-500">{status}</h1>
     <p class="text-xl mt-4">{error.message}</p>
     <a href="/" class="mt-6 btn btn-primary">Go to Home</a>
   </div>
